//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pcsd.Polaris.Common.Model.EntityModel
{
    using GenerateCrmEntityMode;
    using System;
    
    
    [GenerateCrmEntityMode.EntityAttrAttribute("incident")]
    public class CaseDO : EntityBase
    {
        
        private System.Nullable<int> _firstresponseslastatus;
        
        private System.Nullable<int> _warrantytypecode;
        
        private System.Nullable<int> _severitycode;
        
        private System.Nullable<bool> _isfollowuprequired;
        
        private System.Nullable<System.DateTime> _openactionitems_date;
        
        private System.Nullable<bool> _internalnotification;
        
        private System.Nullable<int> _pdtreereasoncode;
        
        private System.Nullable<int> _servicehourcode;
        
        private string _address1_city;
        
        private System.Nullable<int> _resolvebyslastatus;
        
        private System.Nullable<System.Guid> _address1countryid;
        
        private System.Nullable<bool> _blindshipment;
        
        private System.Nullable<System.Guid> _contactid;
        
        private System.Nullable<bool> _isrepeatrepairflag;
        
        private System.Nullable<bool> _clonedcase;
        
        private System.Nullable<bool> _hasdonotdisturb;
        
        private System.Nullable<int> _prioritycode;
        
        private System.Nullable<System.Guid> _slaid;
        
        private System.Nullable<int> _repeatrepaircode;
        
        private System.Nullable<bool> _blockedprofile;
        
        private System.Nullable<bool> _activitiescomplete;
        
        private System.Nullable<bool> _needskbaction;
        
        private string _sdfcode;
        
        private System.Nullable<System.Guid> _slainvokedid;
        
        private string _eticketvalidationcomment;
        
        private System.Nullable<bool> _saassupport;
        
        private System.Nullable<int> _casestatuscode;
        
        private System.Nullable<int> _urgencycode;
        
        private System.Nullable<bool> _needscallback;
        
        private System.Nullable<bool> _pspdpartnerflag;
        
        private string _repairtype;
        
        private System.Nullable<int> _language;
        
        private string _title;
        
        private System.Nullable<bool> _dispatchvalidation;
        
        private System.Nullable<int> _diagnosticreasoncode;
        
        private string _notifieremail;
        
        private string _address1_postalcode;
        
        private System.Nullable<int> _opentodoitems_state;
        
        private System.Nullable<int> _caseclosurewait;
        
        private System.Nullable<bool> _merged;
        
        private System.Nullable<System.Guid> _owningbusinessunit;
        
        private System.Nullable<System.Guid> _customermachineid;
        
        private string _address1_line1;
        
        private System.Nullable<bool> _iskbupdaterequired;
        
        private System.Nullable<System.Guid> _ownerid;
        
        private System.Nullable<bool> _hasregistrationconfirmationemail;
        
        private System.Nullable<bool> _hasharddriveretention;
        
        private System.Nullable<int> _servicestage;
        
        private System.Nullable<int> _openactionitems_state;
        
        private System.Nullable<bool> _isdecrementing;
        
        private string _productid;
        
        private System.Nullable<System.Guid> _createdby;
        
        private System.Nullable<int> _program;
        
        private System.Nullable<bool> _hassealedbattery;
        
        private System.Nullable<int> _opentodoitems;
        
        private System.Nullable<bool> _hastechinstalledcru;
        
        private string _machinetype;
        
        private System.Nullable<int> _daysopen;
        
        private System.Nullable<bool> _hasnotifycustomerofupdates;
        
        private System.Nullable<bool> _routecase;
        
        private System.Nullable<bool> _isescalated;
        
        private System.Nullable<int> _caseorigincode;
        
        private System.Nullable<bool> _isescalationrequired;
        
        private System.Nullable<bool> _isentitlementcheckrequired;
        
        private System.Nullable<System.DateTime> _surveydate;
        
        private System.Nullable<int> _impactcode;
        
        private System.Nullable<bool> _batchimport;
        
        private System.Nullable<int> _openactionitems;
        
        private System.Nullable<int> _accountingindicatorcode;
        
        private System.Nullable<System.Guid> _countryid;
        
        private System.Nullable<bool> _needspopupdate;
        
        private string _firstname;
        
        private System.Nullable<System.DateTime> _warrantyenddate;
        
        private System.Nullable<bool> _necpccreateescalation;
        
        private System.Nullable<int> _test_state;
        
        private System.Nullable<int> _casetype;
        
        private System.Nullable<bool> _hasinternationalentitlement;
        
        private System.Nullable<bool> _followuptaskcreated;
        
        private System.Nullable<System.DateTime> _createdon;
        
        private System.Nullable<System.Guid> _modifiedby;
        
        private System.Nullable<bool> _ispoprequired;
        
        private System.Nullable<bool> _isdispatchvalidation;
        
        private string _lenovoid;
        
        private string _mobilephone2;
        
        private System.Nullable<bool> _billable;
        
        private System.Nullable<System.DateTime> _laststatuschange;
        
        private System.Nullable<bool> _customercontacted;
        
        private System.Nullable<int> _caseclosecounter;
        
        private System.Nullable<bool> _ispopupdaterequired;
        
        private System.Nullable<bool> _isvip;
        
        private System.Nullable<int> _surveymedium;
        
        private System.Nullable<bool> _isvalidentitlement;
        
        private string _mobilephone;
        
        private System.Nullable<bool> _casestatusupdated;
        
        private System.Nullable<bool> _isusedlenovodiagnostics;
        
        private System.Nullable<bool> _casecreatedbypartneruser;
        
        private System.Nullable<bool> _isactionitemrequired;
        
        private System.Nullable<bool> _hasaccidentaldamageprotection;
        
        private string _emailaddress1;
        
        private System.Nullable<bool> _firstresponsesent;
        
        private System.Nullable<int> _servicetypecode;
        
        private System.Nullable<bool> _specialtouchlesseticket;
        
        private string _productserialnumber;
        
        private System.Nullable<int> _laststatuscode;
        
        private System.Nullable<System.Guid> _owningteam;
        
        private System.Nullable<bool> _issalesinquiryrequired;
        
        private System.Nullable<System.DateTime> _openescalations_date;
        
        private System.Nullable<int> _timezoneruleversionnumber;
        
        private System.Nullable<System.Guid> _serviceorg;
        
        private System.Nullable<bool> _carecall;
        
        private System.Nullable<int> _statuscode;
        
        private System.Nullable<System.Guid> _firstresponsesla;
        
        private System.Nullable<System.Guid> _primaryteam;
        
        private System.Nullable<int> _incidentstagecode;
        
        private System.Nullable<System.DateTime> _opentodoitems_date;
        
        private System.Nullable<int> _servicelevelcode;
        
        private string _ticketnumber;
        
        private System.Nullable<System.DateTime> _warrantystartdate;
        
        private System.Nullable<bool> _decremententitlementterm;
        
        private System.Nullable<bool> _hasdonotsurvey;
        
        private System.Nullable<bool> _isusedlenovopdtree;
        
        private System.Nullable<bool> _hassendsurvey;
        
        private System.Nullable<int> _openescalations;
        
        private System.Nullable<bool> _isinwarranty;
        
        private System.Nullable<bool> _emailfaq;
        
        private System.Nullable<int> _openescalations_state;
        
        private System.Nullable<System.DateTime> _modifiedon;
        
        private System.Nullable<System.Guid> _originalowner;
        
        private System.Nullable<System.DateTime> _lastupdatedon;
        
        private System.Nullable<int> _shippingmodelcode;
        
        private System.Guid _id;
        
        private System.Nullable<int> _timeincurrentstatus;
        
        private string _eticketid;
        
        private System.Nullable<bool> _customeraction;
        
        private System.Nullable<System.DateTime> _today;
        
        private System.Nullable<int> _attachmentremark;
        
        private System.Nullable<bool> _touchlesseticket;
        
        private System.Nullable<bool> _checkemail;
        
        private string _lastname;
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "firstresponseslastatus")]
        public virtual System.Nullable<int> firstresponseslastatus
        {
            get
            {
                return this._firstresponseslastatus;
            }
            set
            {
                this._firstresponseslastatus = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_warrantytypecode")]
        public virtual System.Nullable<int> warrantytypecode
        {
            get
            {
                return this._warrantytypecode;
            }
            set
            {
                this._warrantytypecode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "severitycode")]
        public virtual System.Nullable<int> severitycode
        {
            get
            {
                return this._severitycode;
            }
            set
            {
                this._severitycode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isfollowuprequired")]
        public virtual System.Nullable<bool> isfollowuprequired
        {
            get
            {
                return this._isfollowuprequired;
            }
            set
            {
                this._isfollowuprequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_openactionitems_date")]
        public virtual System.Nullable<System.DateTime> openactionitems_date
        {
            get
            {
                return this._openactionitems_date;
            }
            set
            {
                this._openactionitems_date = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_internalnotification")]
        public virtual System.Nullable<bool> internalnotification
        {
            get
            {
                return this._internalnotification;
            }
            set
            {
                this._internalnotification = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_pdtreereasoncode")]
        public virtual System.Nullable<int> pdtreereasoncode
        {
            get
            {
                return this._pdtreereasoncode;
            }
            set
            {
                this._pdtreereasoncode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_servicehourcode")]
        public virtual System.Nullable<int> servicehourcode
        {
            get
            {
                return this._servicehourcode;
            }
            set
            {
                this._servicehourcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_address1_city")]
        public virtual string address1_city
        {
            get
            {
                return this._address1_city;
            }
            set
            {
                this._address1_city = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "resolvebyslastatus")]
        public virtual System.Nullable<int> resolvebyslastatus
        {
            get
            {
                return this._resolvebyslastatus;
            }
            set
            {
                this._resolvebyslastatus = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_address1countryid", "lvdcg_country")]
        public virtual System.Nullable<System.Guid> address1countryid
        {
            get
            {
                return this._address1countryid;
            }
            set
            {
                this._address1countryid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_blindshipment")]
        public virtual System.Nullable<bool> blindshipment
        {
            get
            {
                return this._blindshipment;
            }
            set
            {
                this._blindshipment = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_contactid", "contact")]
        public virtual System.Nullable<System.Guid> contactid
        {
            get
            {
                return this._contactid;
            }
            set
            {
                this._contactid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isrepeatrepairflag")]
        public virtual System.Nullable<bool> isrepeatrepairflag
        {
            get
            {
                return this._isrepeatrepairflag;
            }
            set
            {
                this._isrepeatrepairflag = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_clonedcase")]
        public virtual System.Nullable<bool> clonedcase
        {
            get
            {
                return this._clonedcase;
            }
            set
            {
                this._clonedcase = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasdonotdisturb")]
        public virtual System.Nullable<bool> hasdonotdisturb
        {
            get
            {
                return this._hasdonotdisturb;
            }
            set
            {
                this._hasdonotdisturb = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "prioritycode")]
        public virtual System.Nullable<int> prioritycode
        {
            get
            {
                return this._prioritycode;
            }
            set
            {
                this._prioritycode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "slaid", "sla")]
        public virtual System.Nullable<System.Guid> slaid
        {
            get
            {
                return this._slaid;
            }
            set
            {
                this._slaid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_repeatrepaircode")]
        public virtual System.Nullable<int> repeatrepaircode
        {
            get
            {
                return this._repeatrepaircode;
            }
            set
            {
                this._repeatrepaircode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "blockedprofile")]
        public virtual System.Nullable<bool> blockedprofile
        {
            get
            {
                return this._blockedprofile;
            }
            set
            {
                this._blockedprofile = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "activitiescomplete")]
        public virtual System.Nullable<bool> activitiescomplete
        {
            get
            {
                return this._activitiescomplete;
            }
            set
            {
                this._activitiescomplete = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_needskbaction")]
        public virtual System.Nullable<bool> needskbaction
        {
            get
            {
                return this._needskbaction;
            }
            set
            {
                this._needskbaction = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_sdfcode")]
        public virtual string sdfcode
        {
            get
            {
                return this._sdfcode;
            }
            set
            {
                this._sdfcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "slainvokedid", "sla")]
        public virtual System.Nullable<System.Guid> slainvokedid
        {
            get
            {
                return this._slainvokedid;
            }
            set
            {
                this._slainvokedid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_eticketvalidationcomment")]
        public virtual string eticketvalidationcomment
        {
            get
            {
                return this._eticketvalidationcomment;
            }
            set
            {
                this._eticketvalidationcomment = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_saassupport")]
        public virtual System.Nullable<bool> saassupport
        {
            get
            {
                return this._saassupport;
            }
            set
            {
                this._saassupport = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_casestatuscode")]
        public virtual System.Nullable<int> casestatuscode
        {
            get
            {
                return this._casestatuscode;
            }
            set
            {
                this._casestatuscode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_urgencycode")]
        public virtual System.Nullable<int> urgencycode
        {
            get
            {
                return this._urgencycode;
            }
            set
            {
                this._urgencycode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_needscallback")]
        public virtual System.Nullable<bool> needscallback
        {
            get
            {
                return this._needscallback;
            }
            set
            {
                this._needscallback = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_pspdpartnerflag")]
        public virtual System.Nullable<bool> pspdpartnerflag
        {
            get
            {
                return this._pspdpartnerflag;
            }
            set
            {
                this._pspdpartnerflag = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_repairtype")]
        public virtual string repairtype
        {
            get
            {
                return this._repairtype;
            }
            set
            {
                this._repairtype = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_language")]
        public virtual System.Nullable<int> language
        {
            get
            {
                return this._language;
            }
            set
            {
                this._language = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "title")]
        public virtual string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_dispatchvalidation")]
        public virtual System.Nullable<bool> dispatchvalidation
        {
            get
            {
                return this._dispatchvalidation;
            }
            set
            {
                this._dispatchvalidation = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_diagnosticreasoncode")]
        public virtual System.Nullable<int> diagnosticreasoncode
        {
            get
            {
                return this._diagnosticreasoncode;
            }
            set
            {
                this._diagnosticreasoncode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_notifieremail")]
        public virtual string notifieremail
        {
            get
            {
                return this._notifieremail;
            }
            set
            {
                this._notifieremail = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_address1_postalcode")]
        public virtual string address1_postalcode
        {
            get
            {
                return this._address1_postalcode;
            }
            set
            {
                this._address1_postalcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_opentodoitems_state")]
        public virtual System.Nullable<int> opentodoitems_state
        {
            get
            {
                return this._opentodoitems_state;
            }
            set
            {
                this._opentodoitems_state = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_caseclosurewait")]
        public virtual System.Nullable<int> caseclosurewait
        {
            get
            {
                return this._caseclosurewait;
            }
            set
            {
                this._caseclosurewait = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "merged")]
        public virtual System.Nullable<bool> merged
        {
            get
            {
                return this._merged;
            }
            set
            {
                this._merged = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "owningbusinessunit", "businessunit")]
        public virtual System.Nullable<System.Guid> owningbusinessunit
        {
            get
            {
                return this._owningbusinessunit;
            }
            set
            {
                this._owningbusinessunit = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_customermachineid", "msdyn_customerasset")]
        public virtual System.Nullable<System.Guid> customermachineid
        {
            get
            {
                return this._customermachineid;
            }
            set
            {
                this._customermachineid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_address1_line1")]
        public virtual string address1_line1
        {
            get
            {
                return this._address1_line1;
            }
            set
            {
                this._address1_line1 = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_iskbupdaterequired")]
        public virtual System.Nullable<bool> iskbupdaterequired
        {
            get
            {
                return this._iskbupdaterequired;
            }
            set
            {
                this._iskbupdaterequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Owner", "ownerid", "systemuser")]
        public virtual System.Nullable<System.Guid> ownerid
        {
            get
            {
                return this._ownerid;
            }
            set
            {
                this._ownerid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasregistrationconfirmationemail")]
        public virtual System.Nullable<bool> hasregistrationconfirmationemail
        {
            get
            {
                return this._hasregistrationconfirmationemail;
            }
            set
            {
                this._hasregistrationconfirmationemail = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasharddriveretention")]
        public virtual System.Nullable<bool> hasharddriveretention
        {
            get
            {
                return this._hasharddriveretention;
            }
            set
            {
                this._hasharddriveretention = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "servicestage")]
        public virtual System.Nullable<int> servicestage
        {
            get
            {
                return this._servicestage;
            }
            set
            {
                this._servicestage = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_openactionitems_state")]
        public virtual System.Nullable<int> openactionitems_state
        {
            get
            {
                return this._openactionitems_state;
            }
            set
            {
                this._openactionitems_state = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "isdecrementing")]
        public virtual System.Nullable<bool> isdecrementing
        {
            get
            {
                return this._isdecrementing;
            }
            set
            {
                this._isdecrementing = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_productid")]
        public virtual string productid
        {
            get
            {
                return this._productid;
            }
            set
            {
                this._productid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "createdby", "systemuser")]
        public virtual System.Nullable<System.Guid> createdby
        {
            get
            {
                return this._createdby;
            }
            set
            {
                this._createdby = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_program")]
        public virtual System.Nullable<int> program
        {
            get
            {
                return this._program;
            }
            set
            {
                this._program = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hassealedbattery")]
        public virtual System.Nullable<bool> hassealedbattery
        {
            get
            {
                return this._hassealedbattery;
            }
            set
            {
                this._hassealedbattery = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_opentodoitems")]
        public virtual System.Nullable<int> opentodoitems
        {
            get
            {
                return this._opentodoitems;
            }
            set
            {
                this._opentodoitems = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hastechinstalledcru")]
        public virtual System.Nullable<bool> hastechinstalledcru
        {
            get
            {
                return this._hastechinstalledcru;
            }
            set
            {
                this._hastechinstalledcru = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_machinetype")]
        public virtual string machinetype
        {
            get
            {
                return this._machinetype;
            }
            set
            {
                this._machinetype = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_daysopen")]
        public virtual System.Nullable<int> daysopen
        {
            get
            {
                return this._daysopen;
            }
            set
            {
                this._daysopen = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasnotifycustomerofupdates")]
        public virtual System.Nullable<bool> hasnotifycustomerofupdates
        {
            get
            {
                return this._hasnotifycustomerofupdates;
            }
            set
            {
                this._hasnotifycustomerofupdates = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "routecase")]
        public virtual System.Nullable<bool> routecase
        {
            get
            {
                return this._routecase;
            }
            set
            {
                this._routecase = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "isescalated")]
        public virtual System.Nullable<bool> isescalated
        {
            get
            {
                return this._isescalated;
            }
            set
            {
                this._isescalated = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "caseorigincode")]
        public virtual System.Nullable<int> caseorigincode
        {
            get
            {
                return this._caseorigincode;
            }
            set
            {
                this._caseorigincode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isescalationrequired")]
        public virtual System.Nullable<bool> isescalationrequired
        {
            get
            {
                return this._isescalationrequired;
            }
            set
            {
                this._isescalationrequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isentitlementcheckrequired")]
        public virtual System.Nullable<bool> isentitlementcheckrequired
        {
            get
            {
                return this._isentitlementcheckrequired;
            }
            set
            {
                this._isentitlementcheckrequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_surveydate")]
        public virtual System.Nullable<System.DateTime> surveydate
        {
            get
            {
                return this._surveydate;
            }
            set
            {
                this._surveydate = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_impactcode")]
        public virtual System.Nullable<int> impactcode
        {
            get
            {
                return this._impactcode;
            }
            set
            {
                this._impactcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_batchimport")]
        public virtual System.Nullable<bool> batchimport
        {
            get
            {
                return this._batchimport;
            }
            set
            {
                this._batchimport = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_openactionitems")]
        public virtual System.Nullable<int> openactionitems
        {
            get
            {
                return this._openactionitems;
            }
            set
            {
                this._openactionitems = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_accountingindicatorcode")]
        public virtual System.Nullable<int> accountingindicatorcode
        {
            get
            {
                return this._accountingindicatorcode;
            }
            set
            {
                this._accountingindicatorcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvdcg_countryid", "lvdcg_country")]
        public virtual System.Nullable<System.Guid> countryid
        {
            get
            {
                return this._countryid;
            }
            set
            {
                this._countryid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_needspopupdate")]
        public virtual System.Nullable<bool> needspopupdate
        {
            get
            {
                return this._needspopupdate;
            }
            set
            {
                this._needspopupdate = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_firstname")]
        public virtual string firstname
        {
            get
            {
                return this._firstname;
            }
            set
            {
                this._firstname = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_warrantyenddate")]
        public virtual System.Nullable<System.DateTime> warrantyenddate
        {
            get
            {
                return this._warrantyenddate;
            }
            set
            {
                this._warrantyenddate = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "necpc_necpccreateescalation")]
        public virtual System.Nullable<bool> necpccreateescalation
        {
            get
            {
                return this._necpccreateescalation;
            }
            set
            {
                this._necpccreateescalation = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "new_test_state")]
        public virtual System.Nullable<int> test_state
        {
            get
            {
                return this._test_state;
            }
            set
            {
                this._test_state = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_casetype")]
        public virtual System.Nullable<int> casetype
        {
            get
            {
                return this._casetype;
            }
            set
            {
                this._casetype = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasinternationalentitlement")]
        public virtual System.Nullable<bool> hasinternationalentitlement
        {
            get
            {
                return this._hasinternationalentitlement;
            }
            set
            {
                this._hasinternationalentitlement = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "followuptaskcreated")]
        public virtual System.Nullable<bool> followuptaskcreated
        {
            get
            {
                return this._followuptaskcreated;
            }
            set
            {
                this._followuptaskcreated = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "createdon")]
        public virtual System.Nullable<System.DateTime> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this._createdon = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "modifiedby", "systemuser")]
        public virtual System.Nullable<System.Guid> modifiedby
        {
            get
            {
                return this._modifiedby;
            }
            set
            {
                this._modifiedby = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_ispoprequired")]
        public virtual System.Nullable<bool> ispoprequired
        {
            get
            {
                return this._ispoprequired;
            }
            set
            {
                this._ispoprequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isdispatchvalidation")]
        public virtual System.Nullable<bool> isdispatchvalidation
        {
            get
            {
                return this._isdispatchvalidation;
            }
            set
            {
                this._isdispatchvalidation = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_lenovoid")]
        public virtual string lenovoid
        {
            get
            {
                return this._lenovoid;
            }
            set
            {
                this._lenovoid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_mobilephone2")]
        public virtual string mobilephone2
        {
            get
            {
                return this._mobilephone2;
            }
            set
            {
                this._mobilephone2 = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_billable")]
        public virtual System.Nullable<bool> billable
        {
            get
            {
                return this._billable;
            }
            set
            {
                this._billable = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_laststatuschange")]
        public virtual System.Nullable<System.DateTime> laststatuschange
        {
            get
            {
                return this._laststatuschange;
            }
            set
            {
                this._laststatuschange = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "customercontacted")]
        public virtual System.Nullable<bool> customercontacted
        {
            get
            {
                return this._customercontacted;
            }
            set
            {
                this._customercontacted = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_caseclosecounter")]
        public virtual System.Nullable<int> caseclosecounter
        {
            get
            {
                return this._caseclosecounter;
            }
            set
            {
                this._caseclosecounter = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_ispopupdaterequired")]
        public virtual System.Nullable<bool> ispopupdaterequired
        {
            get
            {
                return this._ispopupdaterequired;
            }
            set
            {
                this._ispopupdaterequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isvip")]
        public virtual System.Nullable<bool> isvip
        {
            get
            {
                return this._isvip;
            }
            set
            {
                this._isvip = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_surveymedium")]
        public virtual System.Nullable<int> surveymedium
        {
            get
            {
                return this._surveymedium;
            }
            set
            {
                this._surveymedium = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isvalidentitlement")]
        public virtual System.Nullable<bool> isvalidentitlement
        {
            get
            {
                return this._isvalidentitlement;
            }
            set
            {
                this._isvalidentitlement = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_mobilephone")]
        public virtual string mobilephone
        {
            get
            {
                return this._mobilephone;
            }
            set
            {
                this._mobilephone = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_casestatusupdated")]
        public virtual System.Nullable<bool> casestatusupdated
        {
            get
            {
                return this._casestatusupdated;
            }
            set
            {
                this._casestatusupdated = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isusedlenovodiagnostics")]
        public virtual System.Nullable<bool> isusedlenovodiagnostics
        {
            get
            {
                return this._isusedlenovodiagnostics;
            }
            set
            {
                this._isusedlenovodiagnostics = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_casecreatedbypartneruser")]
        public virtual System.Nullable<bool> casecreatedbypartneruser
        {
            get
            {
                return this._casecreatedbypartneruser;
            }
            set
            {
                this._casecreatedbypartneruser = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isactionitemrequired")]
        public virtual System.Nullable<bool> isactionitemrequired
        {
            get
            {
                return this._isactionitemrequired;
            }
            set
            {
                this._isactionitemrequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hasaccidentaldamageprotection")]
        public virtual System.Nullable<bool> hasaccidentaldamageprotection
        {
            get
            {
                return this._hasaccidentaldamageprotection;
            }
            set
            {
                this._hasaccidentaldamageprotection = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_emailaddress1")]
        public virtual string emailaddress1
        {
            get
            {
                return this._emailaddress1;
            }
            set
            {
                this._emailaddress1 = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "firstresponsesent")]
        public virtual System.Nullable<bool> firstresponsesent
        {
            get
            {
                return this._firstresponsesent;
            }
            set
            {
                this._firstresponsesent = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_servicetypecode")]
        public virtual System.Nullable<int> servicetypecode
        {
            get
            {
                return this._servicetypecode;
            }
            set
            {
                this._servicetypecode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_specialtouchlesseticket")]
        public virtual System.Nullable<bool> specialtouchlesseticket
        {
            get
            {
                return this._specialtouchlesseticket;
            }
            set
            {
                this._specialtouchlesseticket = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "productserialnumber")]
        public virtual string productserialnumber
        {
            get
            {
                return this._productserialnumber;
            }
            set
            {
                this._productserialnumber = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_laststatuscode")]
        public virtual System.Nullable<int> laststatuscode
        {
            get
            {
                return this._laststatuscode;
            }
            set
            {
                this._laststatuscode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "owningteam", "team")]
        public virtual System.Nullable<System.Guid> owningteam
        {
            get
            {
                return this._owningteam;
            }
            set
            {
                this._owningteam = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_issalesinquiryrequired")]
        public virtual System.Nullable<bool> issalesinquiryrequired
        {
            get
            {
                return this._issalesinquiryrequired;
            }
            set
            {
                this._issalesinquiryrequired = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_openescalations_date")]
        public virtual System.Nullable<System.DateTime> openescalations_date
        {
            get
            {
                return this._openescalations_date;
            }
            set
            {
                this._openescalations_date = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "timezoneruleversionnumber")]
        public virtual System.Nullable<int> timezoneruleversionnumber
        {
            get
            {
                return this._timezoneruleversionnumber;
            }
            set
            {
                this._timezoneruleversionnumber = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_serviceorg", "businessunit")]
        public virtual System.Nullable<System.Guid> serviceorg
        {
            get
            {
                return this._serviceorg;
            }
            set
            {
                this._serviceorg = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_carecall")]
        public virtual System.Nullable<bool> carecall
        {
            get
            {
                return this._carecall;
            }
            set
            {
                this._carecall = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Status", "statuscode")]
        public virtual System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this._statuscode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_firstresponsesla", "slakpiinstance")]
        public virtual System.Nullable<System.Guid> firstresponsesla
        {
            get
            {
                return this._firstresponsesla;
            }
            set
            {
                this._firstresponsesla = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_primaryteam", "team")]
        public virtual System.Nullable<System.Guid> primaryteam
        {
            get
            {
                return this._primaryteam;
            }
            set
            {
                this._primaryteam = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "incidentstagecode")]
        public virtual System.Nullable<int> incidentstagecode
        {
            get
            {
                return this._incidentstagecode;
            }
            set
            {
                this._incidentstagecode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_opentodoitems_date")]
        public virtual System.Nullable<System.DateTime> opentodoitems_date
        {
            get
            {
                return this._opentodoitems_date;
            }
            set
            {
                this._opentodoitems_date = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_servicelevelcode")]
        public virtual System.Nullable<int> servicelevelcode
        {
            get
            {
                return this._servicelevelcode;
            }
            set
            {
                this._servicelevelcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "ticketnumber")]
        public virtual string ticketnumber
        {
            get
            {
                return this._ticketnumber;
            }
            set
            {
                this._ticketnumber = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_warrantystartdate")]
        public virtual System.Nullable<System.DateTime> warrantystartdate
        {
            get
            {
                return this._warrantystartdate;
            }
            set
            {
                this._warrantystartdate = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "decremententitlementterm")]
        public virtual System.Nullable<bool> decremententitlementterm
        {
            get
            {
                return this._decremententitlementterm;
            }
            set
            {
                this._decremententitlementterm = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvdcg_hasdonotsurvey")]
        public virtual System.Nullable<bool> hasdonotsurvey
        {
            get
            {
                return this._hasdonotsurvey;
            }
            set
            {
                this._hasdonotsurvey = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isusedlenovopdtree")]
        public virtual System.Nullable<bool> isusedlenovopdtree
        {
            get
            {
                return this._isusedlenovopdtree;
            }
            set
            {
                this._isusedlenovopdtree = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_hassendsurvey")]
        public virtual System.Nullable<bool> hassendsurvey
        {
            get
            {
                return this._hassendsurvey;
            }
            set
            {
                this._hassendsurvey = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_openescalations")]
        public virtual System.Nullable<int> openescalations
        {
            get
            {
                return this._openescalations;
            }
            set
            {
                this._openescalations = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_isinwarranty")]
        public virtual System.Nullable<bool> isinwarranty
        {
            get
            {
                return this._isinwarranty;
            }
            set
            {
                this._isinwarranty = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "necpc_emailfaq")]
        public virtual System.Nullable<bool> emailfaq
        {
            get
            {
                return this._emailfaq;
            }
            set
            {
                this._emailfaq = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_openescalations_state")]
        public virtual System.Nullable<int> openescalations_state
        {
            get
            {
                return this._openescalations_state;
            }
            set
            {
                this._openescalations_state = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "modifiedon")]
        public virtual System.Nullable<System.DateTime> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this._modifiedon = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Lookup", "lvidg_originalowner", "systemuser")]
        public virtual System.Nullable<System.Guid> originalowner
        {
            get
            {
                return this._originalowner;
            }
            set
            {
                this._originalowner = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_lastupdatedon")]
        public virtual System.Nullable<System.DateTime> lastupdatedon
        {
            get
            {
                return this._lastupdatedon;
            }
            set
            {
                this._lastupdatedon = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Picklist", "lvidg_shippingmodelcode")]
        public virtual System.Nullable<int> shippingmodelcode
        {
            get
            {
                return this._shippingmodelcode;
            }
            set
            {
                this._shippingmodelcode = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Uniqueidentifier", "incidentid")]
        public override System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_timeincurrentstatus")]
        public virtual System.Nullable<int> timeincurrentstatus
        {
            get
            {
                return this._timeincurrentstatus;
            }
            set
            {
                this._timeincurrentstatus = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_eticketid")]
        public virtual string eticketid
        {
            get
            {
                return this._eticketid;
            }
            set
            {
                this._eticketid = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_customeraction")]
        public virtual System.Nullable<bool> customeraction
        {
            get
            {
                return this._customeraction;
            }
            set
            {
                this._customeraction = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("DateTime", "lvidg_today")]
        public virtual System.Nullable<System.DateTime> today
        {
            get
            {
                return this._today;
            }
            set
            {
                this._today = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Integer", "lvidg_attachmentremark")]
        public virtual System.Nullable<int> attachmentremark
        {
            get
            {
                return this._attachmentremark;
            }
            set
            {
                this._attachmentremark = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "lvidg_touchlesseticket")]
        public virtual System.Nullable<bool> touchlesseticket
        {
            get
            {
                return this._touchlesseticket;
            }
            set
            {
                this._touchlesseticket = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("Boolean", "checkemail")]
        public virtual System.Nullable<bool> checkemail
        {
            get
            {
                return this._checkemail;
            }
            set
            {
                this._checkemail = value;
            }
        }
        
        [GenerateCrmEntityMode.EntityFieldAttrAttribute("String", "lvidg_lastname")]
        public virtual string lastname
        {
            get
            {
                return this._lastname;
            }
            set
            {
                this._lastname = value;
            }
        }
    }
}
